/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
          "surface-container-high": "var(--color-surface-container-high)",
          "on-surface-variant": "var(--color-on-surface-variant)",
          "inverse-primary": "var(--color-inverse-primary)",
          "error": "var(--color-error)",
          "primary": "var(--color-primary)",
          "tertiary-fixed": "var(--color-tertiary-fixed)",
          "on-secondary-container": "var(--color-on-secondary-container)",
          "surface-variant": "var(--color-surface-variant)",
          "error-container": "var(--color-error-container)",
          "tertiary-container": "var(--color-tertiary-container)",
          "surface-bright": "var(--color-surface-bright)",
          "primary-container": "var(--color-primary-container)",
          "surface-container-highest": "var(--color-surface-container-highest)",
          "on-error": "var(--color-on-error)",
          "on-background": "var(--color-on-background)",
          "surface-container-low": "var(--color-surface-container-low)",
          "on-primary": "var(--color-on-primary)",
          "secondary": "var(--color-secondary)",
          "tertiary": "var(--color-tertiary)",
          "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
          "outline-variant": "var(--color-outline-variant)",
          "on-surface": "var(--color-on-surface)",
          "primary-fixed": "var(--color-primary-fixed)",
          "primary-fixed-dim": "var(--color-primary-fixed-dim)",
          "surface-container-lowest": "var(--color-surface-container-lowest)",
          "on-primary-fixed": "var(--color-on-primary-fixed)",
          "surface-dim": "var(--color-surface-dim)",
          "on-secondary-fixed": "var(--color-on-secondary-fixed)",
          "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
          "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
          "surface-container": "var(--color-surface-container)",
          "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
          "outline": "var(--color-outline)",
          "on-tertiary-container": "var(--color-on-tertiary-container)",
          "on-primary-container": "var(--color-on-primary-container)",
          "background": "var(--color-background)",
          "on-secondary": "var(--color-on-secondary)",
          "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
          "surface": "var(--color-surface)",
          "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
          "on-error-container": "var(--color-on-error-container)",
          "surface-tint": "var(--color-surface-tint)",
          "on-tertiary": "var(--color-on-tertiary)",
          "inverse-surface": "var(--color-inverse-surface)",
          "secondary-fixed": "var(--color-secondary-fixed)",
          "inverse-on-surface": "var(--color-inverse-on-surface)",
          "secondary-container": "var(--color-secondary-container)",
          "perf-0": "var(--color-perf-0)",
          "perf-1": "var(--color-perf-1)",
          "perf-2": "var(--color-perf-2)",
          "perf-3": "var(--color-perf-3)",
          "perf-4": "var(--color-perf-4)",
          "perf-5": "var(--color-perf-5)",
          "perf-6": "var(--color-perf-6)",
          "perf-7": "var(--color-perf-7)",
          "perf-8": "var(--color-perf-8)",
          "perf-9": "var(--color-perf-9)",
          "perf-10": "var(--color-perf-10)"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "gutter": "16px",
          "container-max-width": "1120px",
          "margin-mobile": "16px",
          "margin-desktop": "48px",
          "unit": "4px"
      },
      "fontFamily": {
          "body-lg": ["Inter"],
          "headline-lg-mobile": ["Inter"],
          "mono-data": ["Geist"],
          "body-md": ["Inter"],
          "headline-md": ["Inter"],
          "headline-lg": ["Inter"],
          "label-sm": ["Inter"]
      },
      "fontSize": {
          "body-lg": ["16px", { "lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400" }],
          "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
          "mono-data": ["14px", { "lineHeight": "1", "letterSpacing": "-0.01em", "fontWeight": "400" }],
          "body-md": ["14px", { "lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400" }],
          "headline-md": ["20px", { "lineHeight": "1.4", "letterSpacing": "-0.01em", "fontWeight": "600" }],
          "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }],
          "label-sm": ["12px", { "lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
