/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
          "surface-container-high": "#e9e7ed",
          "on-surface-variant": "#444748",
          "inverse-primary": "#c8c6c5",
          "error": "#ba1a1a",
          "primary": "#000000",
          "tertiary-fixed": "#e6e1df",
          "on-secondary-container": "#616267",
          "surface-variant": "#e3e2e7",
          "error-container": "#ffdad6",
          "tertiary-container": "#1c1b1a",
          "surface-bright": "#faf9fe",
          "primary-container": "#1c1b1b",
          "surface-container-highest": "#e3e2e7",
          "on-error": "#ffffff",
          "on-background": "#1a1b1f",
          "surface-container-low": "#f4f3f8",
          "on-primary": "#ffffff",
          "secondary": "#5d5e63",
          "tertiary": "#000000",
          "on-secondary-fixed-variant": "#45474b",
          "outline-variant": "#c4c7c7",
          "on-surface": "#1a1b1f",
          "primary-fixed": "#e5e2e1",
          "primary-fixed-dim": "#c8c6c5",
          "surface-container-lowest": "#ffffff",
          "on-primary-fixed": "#1c1b1b",
          "surface-dim": "#dad9df",
          "on-secondary-fixed": "#1a1c1f",
          "secondary-fixed-dim": "#c6c6cb",
          "on-tertiary-fixed-variant": "#484645",
          "surface-container": "#eeedf3",
          "on-tertiary-fixed": "#1c1b1a",
          "outline": "#747878",
          "on-tertiary-container": "#868381",
          "on-primary-container": "#858383",
          "background": "#faf9fe",
          "on-secondary": "#ffffff",
          "tertiary-fixed-dim": "#cac6c3",
          "surface": "#faf9fe",
          "on-primary-fixed-variant": "#474646",
          "on-error-container": "#93000a",
          "surface-tint": "#5f5e5e",
          "on-tertiary": "#ffffff",
          "inverse-surface": "#2f3034",
          "secondary-fixed": "#e2e2e7",
          "inverse-on-surface": "#f1f0f5",
          "secondary-container": "#dfdfe4",
          "perf-0": "#eeedf3",
          "perf-1": "#d1e7dd",
          "perf-2": "#a3cfbb",
          "perf-3": "#75b798",
          "perf-4": "#479f76",
          "perf-5": "#198754",
          "perf-6": "#146c43",
          "perf-7": "#0f5132",
          "perf-8": "#0a3622",
          "perf-9": "#051b11",
          "perf-10": "#000000"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "gutter": "16px",
          "container-max-width": "1120px",
          "margin-mobile": "16px",
          "margin-desktop": "48px",
          "unit": "4px"
      },
      "fontFamily": {
          "body-lg": ["Inter"],
          "headline-lg-mobile": ["Inter"],
          "mono-data": ["Geist"],
          "body-md": ["Inter"],
          "headline-md": ["Inter"],
          "headline-lg": ["Inter"],
          "label-sm": ["Inter"]
      },
      "fontSize": {
          "body-lg": ["16px", { "lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400" }],
          "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
          "mono-data": ["14px", { "lineHeight": "1", "letterSpacing": "-0.01em", "fontWeight": "400" }],
          "body-md": ["14px", { "lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400" }],
          "headline-md": ["20px", { "lineHeight": "1.4", "letterSpacing": "-0.01em", "fontWeight": "600" }],
          "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }],
          "label-sm": ["12px", { "lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
