const fs = require('fs');

const ICONS = [
  'schedule', 'error', 'sync', 'calendar_today', 'bar_chart', 'arrow_forward',
  'event_upcoming', 'close', 'visibility_off', 'visibility', 'fullscreen',
  'event_busy', 'trending_down', 'rocket_launch', 'add', 'done_all',
  'workspace_premium', 'arrow_back', 'check', 'logout', 'inbox', 'delete',
  'alarm', 'bedtime', 'hourglass_empty', 'fitness_center', 'directions_walk',
  'water_drop', 'restaurant', 'local_dining', 'psychology', 'timer',
  'menu_book', 'school', 'smartphone', 'self_improvement', 'edit_note',
  'ac_unit', 'mood', 'bolt', 'no_drinks', 'smoke_free', 'person', 'home'
];

async function main() {
  const iconData = {};
  
  for (const icon of ICONS) {
    const url = `https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/${icon}/default/24px.svg`;
    try {
      const res = await fetch(url);
      if (!res.ok) throw new Error(`Failed to fetch ${icon}: ${res.status}`);
      const svg = await res.text();
      
      // Extract the inner HTML of the SVG (paths, rects, etc)
      const innerMatch = svg.match(/<svg[^>]*>([\s\S]*?)<\/svg>/);
      if (innerMatch) {
        // Need to replace fill-rule, clip-rule, etc to camelCase for React
        let inner = innerMatch[1]
          .replace(/fill-rule/g, 'fillRule')
          .replace(/clip-rule/g, 'clipRule')
          .replace(/stroke-width/g, 'strokeWidth')
          .replace(/stroke-linecap/g, 'strokeLinecap')
          .replace(/stroke-linejoin/g, 'strokeLinejoin');
          
        iconData[icon] = inner.trim();
        console.log(`Fetched ${icon}`);
      }
    } catch (e) {
      console.error(e);
    }
  }

  const componentCode = `// Generated by scripts/fetch_icons.js
import React from 'react';

const ICON_PATHS = {
${Object.entries(iconData).map(([name, path]) => `  '${name}': <>\n    ${path}\n  </>,`).join('\n')}
};

export default function Icon({ name, className = '', style = {}, filled = false }) {
  const inner = ICON_PATHS[name];
  if (!inner) {
    console.warn(\`Icon \${name} not found\`);
    return null;
  }
  
  return (
    <svg 
      xmlns="http://www.w3.org/2000/svg" 
      viewBox="0 -960 960 960" 
      className={className} 
      style={{
        width: '1em',
        height: '1em',
        fill: 'currentColor',
        display: 'inline-block',
        verticalAlign: 'middle',
        ...style
      }}
    >
      {inner}
    </svg>
  );
}
`;

  fs.writeFileSync('./src/components/Icon.jsx', componentCode);
  console.log('Icon.jsx generated successfully.');
}

main();
